const divideSentences = [
  "The quotient of the numbers is",
  "When you divide the first number by the second, you get",
  "If you divide those numbers, the result is",
  "The division yields",
  "The answer from dividing the numbers is",
  "The outcome of the division is",
  "Dividing the numbers results in",
  "You obtain the quotient",
  "By dividing, you get",
  "The division produces",
  "The numbers divide to give",
  "The result of the division operation is",
  "The quotient obtained by dividing is",
  "When you perform the division, you obtain",
  "After dividing, you get",
  "The division yields a quotient of",
  "Dividing the numbers gives",
  "By dividing the numbers, you obtain",
  "The outcome obtained from dividing is",
  "The quotient derived from dividing is",
  "When you divide, you get",
  "The result after dividing the numbers is",
  "Dividing the numbers produces",
  "You obtain the result",
  "By performing the division, you get",
  "The division operation results in",
  "The quotient obtained by dividing the numbers is",
  "When you divide the numbers, the result is",
  "Dividing gives",
  "By dividing, you derive",
  "The outcome of the division operation is",
  "The quotient derived from dividing the numbers is"
];
