const logSentences = [
    "The natural logarithm of the number is",
    "When you take the natural logarithm of the number, you get",
    "The natural logarithm is",
    "The logarithm of the number in base e is",
    "The value of the natural logarithm for the given number is",
    "The result of applying the natural logarithm to the number is",
    "By using the natural logarithm function on the number, you obtain",
    "The number, when subjected to the natural logarithm operation, yields",
    "Taking the natural logarithm of the number gives",
    "The output of the natural logarithm for the number is",
    "When the number is passed through the natural logarithm function, the resulting value is",
    "The natural logarithm function yields the exponent needed to obtain the number",
    "Applying the natural logarithm to the number gives its logarithmic representation",
    "The natural logarithm provides the power to which the base (e) must be raised to obtain the number",
    "The number can be expressed as e raised to the power of its natural logarithm",
    "The natural logarithm reveals the exponent required to produce the number using the base (e)",
    "The logarithm function in base e gives the natural logarithm of the number",
];
