const multiplySentences = [
  "The product of the numbers is",
  "When you multiply those numbers together, you get",
  "If you multiply those numbers, the result is",
  "The answer to multiplying those numbers is",
  "The product of those numbers is",
  "The result of multiplying those numbers is",
  "The outcome of multiplying those numbers is",
  "The consequence of multiplying those numbers is",
  "The sum of multiplying those numbers is",
  "The total of multiplying those numbers is",
  "The sum total of multiplying those numbers is",
  "The total sum of multiplying those numbers is",
  "The product of multiplying those numbers together is",
  "The result of multiplying those numbers together is",
  "The outcome of multiplying those numbers together is",
  "The consequence of multiplying those numbers together is",
  "The sum of multiplying those numbers together is",
  "The total of multiplying those numbers together is",
  "The sum total of multiplying those numbers together is",
  "The product of multiplying those numbers with each other is",
  "The result of multiplying those numbers with each other is",
  "The outcome of multiplying those numbers with each other is",
  "The consequence of multiplying those numbers with each other is",
  "The sum of multiplying those numbers with each other is",
  "The total of multiplying those numbers with each other is",
  "The sum total of multiplying those numbers with each other is",
  "The product of multiplying those numbers using multiplication is",
  "The result of multiplying those numbers using multiplication is",
  "The outcome of multiplying those numbers using multiplication is",
  "The consequence of multiplying those numbers using multiplication is",
  "The sum of multiplying those numbers using multiplication is",
  "The total of multiplying those numbers using multiplication is",
  "The sum total of multiplying those numbers using multiplication is",
  "The product of multiplying those numbers using times is",
  "The result of multiplying those numbers using times is",
  "The outcome of multiplying those numbers using times is",
  "The consequence of multiplying those numbers using times is",
  "The sum of multiplying those numbers using times is",
  "The total of multiplying those numbers using times is",
  "The sum total of multiplying those numbers using times is",
  "The product of multiplying those numbers using the times symbol is",
  "The result of multiplying those numbers using the times symbol is",
  "The outcome of multiplying those numbers using the times symbol is",
  "The consequence of multiplying those numbers using the times symbol is",
  "The sum of multiplying those numbers using the times symbol is",
  "The total of multiplying those numbers using the times symbol is",
  "The sum total of multiplying those numbers using the times symbol is",
  "The product of multiplying those numbers using the multiplication sign is",
  "The result of multiplying those numbers using the multiplication sign is",
  "The outcome of multiplying those numbers using the multiplication sign is",
  "The consequence of multiplying those numbers using the multiplication sign is",
  "The sum of multiplying those numbers using the multiplication sign is",
  "The total of multiplying those numbers using the multiplication sign is",
  "The sum total of multiplying those numbers using the multiplication sign is",
  "The product of those numbers is equal to",
  "The result of those numbers is equal to",
  "The outcome of those numbers is equal to",
  "The consequence of those numbers is equal to",
  "The sum of those numbers is equal to",
  "The total of those numbers is equal to",
  "The sum total of those numbers is equal to",
  "The product of those numbers multiplied together is equal to",
  "The result of those numbers multiplied together is equal to",
  "The outcome of those numbers multiplied together is equal to",
  "The consequence of those numbers multiplied together is equal to",
  "The sum of those numbers multiplied together is equal to",
  "The total of those numbers multiplied together is equal to",
  "The sum total of those numbers multiplied together is equal to"
];
