const operationSynonyms = {
    "add": ["sum", "plus", "+", "addition", "add up", "increment", "augment", "append", "total", "tally", "aggregate", "combine", "join", "amass", "pile up", "accumulate", "totalize", "count", "enlarge", "increase", "boost", "enhance", "amplify", "expand"],
    "subtract": ["difference", "minus", "-", "subtraction", "subtract from", "decrement", "deduct", "remove", "take away", "reduce", "diminish", "lessen", "deplete", "abate", "retrench", "withdraw", "discount", "omit", "eliminate", "curtail", "trim", "cut back", "shrink", "downsize"],
    "multiply": ["product", "times", "*", "multiplication", "multiply by", "times by", "multiply with", "scale", "increase", "enlarge", "grow", "proliferate", "reproduce", "amplify", "augment", "inflate", "expand", "extend", "spread", "propagate", "dilate", "multiply together", "duplicate", "replicate"],
    "divide": ["quotient", "/", "division", "divide by", "split", "partition", "separate", "distribute", "allocate", "share", "apportion", "dispense", "subdivide", "fractionate", "break up", "segment", "break down", "fraction", "dissect", "break apart", "fragment", "chop", "slice", "cut"],
    "exponentiation": ["exponent", "power", "^", "**", "raise to the power of", "to the power", "potentiation", "index", "degree", "magnify", "enlarge", "expand", "amplify", "intensify", "escalate", "heighten", "strengthen", "boost", "increase", "augment", "empower", "uplift", "fortify", "enhance"],
    "sqrt": ["square root", "√", "root", "radical", "square root of", "principal square root", "find the square root of", "calculate the square root of", "extract the square root of", "determine the square root of", "resolve the square root of", "uncover the square root of", "ascertain the square root of", "establish the square root of", "reveal the square root of", "locate the square root of", "obtain the square root of", "discover the square root of", "expose the square root of", "unveil the square root of", "detect the square root of", "retrieve the square root of", "procure the square root of"],
    "log": ["logarithm", "logarithmic", "log base", "logarithm with base", "log of", "logarithm of", "calculate the logarithm of", "determine the logarithm of", "find the logarithm of", "resolve the logarithm of", "ascertain the logarithm of", "establish the logarithm of", "uncover the logarithm of", "reveal the logarithm of", "obtain the logarithm of", "discover the logarithm of", "expose the logarithm of", "unveil the logarithm of", "detect the logarithm of", "retrieve the logarithm of", "procure the logarithm of", "compute the logarithm of", "evaluate the logarithm of"],
    "sin": ["sine", "sinus"],
    "cos": ["cosine", "cosinus"],
    "tan": ["tangent"],
    "abs": ["absolute value", "magnitude", "absoluteness", "modulus", "absolute magnitude", "absolute quantity", "absolute worth", "positive value", "non-negative value", "total", "complete", "whole", "full", "entire", "pure", "sheer", "unadulterated", "unalloyed", "utter", "outright", "unmitigated", "unqualified", "unrestricted", "unreserved"],
    "floor": ["round down", "round to the lower integer", "round to the left", "truncate", "round off", "approximate downwards", "disregard decimals", "chop off", "ignore fractional part", "eliminate remainder", "drop down", "cut down", "remove decimal places", "discard fractions", "reduce to whole number", "strip decimal", "chop down", "cancel out decimal", "dismiss fraction", "cut off decimals", "ignore remainder", "neglect fractional", "remove digits after decimal", "eliminate fractional part"],
    "ceil": ["round up", "round to the higher integer", "round to the right", "approximate upwards", "consider decimal", "keep decimals", "account for fractional part", "include remainder", "add to next integer", "raise to nearest whole number", "increment to next integer", "add 1 to integer part", "propagate decimal places", "augment fractional part", "increase to next whole number", "extend to higher integer", "promote to nearest integer", "upward round", "up-round", "carry decimals", "upsize integer part", "round towards positive infinity", "increment by 1", "round away from zero"]
};
