const sqrtSentences = [
    "The square root of the number is",
    "When you take the square root of the number, you get",
    "The square root is",
    "The square root of the given number yields",
    "Taking the square root gives us",
    "After applying the square root operation, we obtain",
    "The result of the square root calculation is",
    "By finding the square root, we obtain",
    "When we compute the square root, we arrive at",
    "The value of the square root is",
    "Upon taking the square root, we find",
    "The number's square root is equal to",
    "The principal square root is",
    "When we extract the square root, we obtain",
    "The square root, when evaluated, gives",
    "The square root can be represented as",
    "Obtaining the square root yields",
    "By calculating the square root, we get",
    "The square root of the given quantity is",
    "Taking the root square gives",
];
