const subtractSentences = [
  "The difference of the numbers is",
  "When you subtract those numbers, you get",
  "If you take the second number from the first, the result is",
  "The first number minus the second number is",
  "The difference between the two numbers is",
  "The result of subtracting the two numbers is",
  "The second number subtracted from the first number is",
  "When you take the first number and subtract the second number, you get",
  "The difference between the first number and the second number is",
  "The first number minus the second number equals",
  "The second number subtracted from the first number equals",
  "The difference of the two numbers is equal to",
  "The result of subtracting the two numbers is equal to",
  "The second number subtracted from the first number is equal to",
  "When you take the first number and subtract the second number, you get the same as",
  "The difference between the first number and the second number is the same as",
  "The first number minus the second number is the same as",
  "The second number subtracted from the first number is the same as",
  "The difference of the two numbers is identical to",
  "The result of subtracting the two numbers is identical to",
  "The second number subtracted from the first number is identical to",
  "When you take the first number and subtract the second number, you get the same result as",
  "The difference between the first number and the second number is the same result as",
  "The first number minus the second number is the same result as",
  "The second number subtracted from the first number is the same result as",
  "The difference of the two numbers is equivalent to",
  "The result of subtracting the two numbers is equivalent to",
  "The second number subtracted from the first number is equivalent to",
  "When you take the first number and subtract the second number, you get the same outcome as",
  "The difference between the first number and the second number is the same outcome as",
  "The first number minus the second number is the same outcome as",
  "The second number subtracted from the first number is the same outcome as",
  "The difference of the two numbers is tantamount to",
  "The result of subtracting the two numbers is tantamount to",
  "The second number subtracted from the first number is tantamount to",
  "When you take the first number and subtract the second number, you get the same effect as",
  "The difference between the first number and the second number is the same effect as",
  "The first number minus the second number is the same effect as",
  "The second number subtracted from the first number is the same effect as",
  "The difference of the two numbers is comparable to",
  "The result of subtracting the two numbers is comparable to",
  "The second number subtracted from the first number is comparable to",
  "When you take the first number and subtract the second number, you get the same outcome as",
  "The difference between the first number and the second number is the same outcome as",
  "The first number minus the second number is the same outcome as",
  "The second number subtracted from the first number is the same outcome as",
  "The difference of the two numbers is analogous to",
  "The result of subtracting the two numbers is analogous to",
  "The second number subtracted from the first number is analogous to",
  "When you take the first number and subtract the second number, you get the same result as",
  "The difference between the first number and the second number is the same result as",
  "The first number minus the second number is the same result as",
  "The second number subtracted from the first number is the same result as",
  "The difference of the two numbers is nearly the same as",
  "The result of subtracting the two numbers is nearly the same as",
  "The second number subtracted from the first number is nearly the same as",
  "When you take the first number and subtract the second number, you get an outcome that is nearly the same as",
  "The difference between the first number and the second number is an outcome that is nearly the same as",
  "The first number minus the second number is an outcome that is nearly the same as",
  "The second number subtracted from the first number is an outcome that is nearly the same as",
  "The difference of the two numbers is nearly identical to",
  "The result of subtracting the two numbers is"
];
